### ISSUE TITLE
Support JsonSerializerOptions options in Copy operation 

### ISSUE THREAD

**Issue by vahoang** [Havunen/SystemTextJsonPatch#13]
#### Description

Currently only the `Copy` operation at [here](https://github.com/Havunen/SystemTextJsonPatch/blob/32780d93476fa33c3aa7810c94447ffe4e74b13f/SystemTextJsonPatch/Adapters/ObjectAdapter.cs#L211) does not use the provided `JsonSerializerOptions`.

#### To Reproduce
- Create a custom converter (ex:  a converter to support new type `DateOnly`)
- Add the converter in the JsonSerializerOptions options
```
JsonSerializerOptions jsonOptions = new JsonSerializerOptions()
{
   Converters =
   {
      new JsonPatchDocumentConverterFactory(),
      // below is the custom converter
      new DateOnlyConverter(),
   },
};
````
- Try to use json patch document that will trigger the custom converter (ex: in this case use model with `DateOnly` attribute)
- All other operations work fine except `Copy`.

#### Tasks
-  [ ] Pass the provided `JsonSerializerOptions options` to [`ConversionResultProvider.TryCopyTo`](https://github.com/Havunen/SystemTextJsonPatch/blob/32780d93476fa33c3aa7810c94447ffe4e74b13f/SystemTextJsonPatch/Adapters/ObjectAdapter.cs#L227)
- [ ] Use the `options` when try to deserialize the object in [TryCopyTo ](https://github.com/Havunen/SystemTextJsonPatch/blob/main/SystemTextJsonPatch/Internal/ConversionResultProvider.cs#L87)method
- [ ] Write test cases

**Comment by vahoang** [comment]
@Havunen Can help me double check if the issue is valid and if I can help you to fix it, many thanks!!

**Comment by Havunen** [comment]
Yeah, I think it should ideally use the provided options in those Serialize methods, but there was some issue where the logic got into infinite loop because it was calling itself. That needs to be tested.

**Comment by vahoang** [comment]
@Havunen Do you recall how did you end up with such infinite loop cause I did some tests and cannot reproduce it.

**Comment by Havunen** [comment]
Ah, it seems TryConvertTo was already passing the json serializer options there, I believe I fixed it at some point then. Yeah this sounds like a bug

**Comment by Havunen** [comment]
Fixed in v0.0.9

**Comment by vahoang** [comment]
Thanks for the swift replies and fix !!
